name: create release

on: push

permissions:
  contents: write

jobs:
  build:
    name: build and create release
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2

      - name: setup go env
        uses: actions/setup-go@v4.0.0
        with:
          go-version-file: './go.mod'
        if: startsWith(github.ref, 'refs/tags/')

      - name: create binary directory
        run: mkdir bin
        if: startsWith(github.ref, 'refs/tags/')

      - name: build binaries
        run: bash ./build.sh
        if: startsWith(github.ref, 'refs/tags/')

      - name: create release
        id: create_release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          name: ${{ github.ref_name }}
          body: ${{ github.ref_name }}
          draft: false
          prerelease: false
          files: bin/*
